name: Integration Tests

on:
  workflow_dispatch:
    inputs:
      verbose:
        description: "Verbose output"
        required: false
        default: false
        type: boolean

jobs:
  integration-test:
    name: Integration Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/deno
          key: ${{ runner.os }}-deno-${{ hashFiles('**/deno.lock') }}
          restore-keys: |
            ${{ runner.os }}-deno-

      - name: Run integration tests
        run: deno task test:integration
        env:
          VERBOSE: ${{ github.event.inputs.verbose || 'false' }}
